# Generated by Django 4.1.7 on 2023-02-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_time',
            new_name='contact_date',
        ),
    ]
